CAT_COLUMNS = [
    'utm_source',
    'utm_medium',
    'utm_campaign',
    'utm_adcontent',
    'utm_keyword',
    'device_category',
    'device_os',
    'device_brand',
    'device_model',
    'device_screen_resolution',
    'device_browser',
    'geo_country',
    'geo_city',
]
